name: Publish documentation

on:
    push:
        branches:
            - 'main'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                submodules: 'true'
            
            - name: CMake configure doxygen
              run: cmake . -DNTP_ENABLE_DOCS_ONLY=ON

#            - name: Generate Documentation
#              uses: mattnotmitt/doxygen-action@v1.9.4
#
#            - name: Publish generated content to GitHub Pages
#              uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
#              with:
#                dir: docs/html
#                branch: gh-pages
#                token: ${{ secrets.ACCESS_TOKEN }}
